apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: k-s-training
build:
  artifacts:
  - image: docker.io/k8s-training-app/things
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
