apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: things
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: things
  type: NodePort
status:
  loadBalancer: {}
